### PR TITLE
fix datagrams

### PR DESCRIPTION
**Pull request by creeper123123321**

### CODE REVIEW

**Comment by rtm516** [comment]
This should be PRd to the upstream repo (https://github.com/Steveice10/PacketLib) and then we will pull the change down from there.

**Comment by creeper123123321** [comment]
Upstream isn't affected with that bug

**Comment by Camotoy** [comment]
Yes, according to the stack trace provided in the issue, it would be my changes that I haven't upstreamed myself that caused the issue.

**Comment by Camotoy** [comment]
Thanks! I'm not touching an IDE for the weekend but @rtm516 or someone else is free to update the PacketLib dependency in Geyser. Otherwise, I'll use this in Geyser on Monday.

**Pull request merged**
